services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ecom
      POSTGRES_USER: ecom
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecom -d ecom"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  web:
    build: .
    user: root
    command: ["/app/scripts/entrypoint.sh"]
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      DEBUG: "False"
      ALLOW_MOCK_PAYMENTS: "False"
      DEFAULT_PAYMENT_GATEWAY: ${DEFAULT_PAYMENT_GATEWAY:-chapa}
      USE_REDIS_CACHE: "True"
      SEED_CATALOG: ${SEED_CATALOG:-True}
      DATABASE_URL: postgres://ecom:${POSTGRES_PASSWORD}@db:5432/ecom
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_TASK_ALWAYS_EAGER: "False"
      SECURE_SSL_REDIRECT: ${SECURE_SSL_REDIRECT:-False}
    volumes:
      - media_data:/app/media
      - static_data:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    expose:
      - "8000"

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "${API_PORT:-80}:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - media_data:/app/media:ro
      - static_data:/app/staticfiles:ro
    depends_on:
      - web
    restart: unless-stopped

  worker:
    build: .
    command: celery -A config worker -l info
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      DEBUG: "False"
      DATABASE_URL: postgres://ecom:${POSTGRES_PASSWORD}@db:5432/ecom
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_TASK_ALWAYS_EAGER: "False"
    volumes:
      - media_data:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      web:
        condition: service_started
    restart: unless-stopped

volumes:
  pgdata:
  media_data:
  static_data:
